### PR TITLE
Add new functions for working with lists?

### PR DESCRIPTION
**Pull request by mgold**
The PR adds `mapOverList`, `foldOverList`, and `scanOverList`. I'm seeking feedback as to whether I should add them (are they useful?), as well as thoughts on naming and documenting. Paging @rtfeldman, @nphollon, @jvoigtlaender.

A fellow on Slack was having difficulty with a problem these functions might solve:

> I’m trying to convert a `foldl` which does a Random.step on each iteration into a generator, any tips on how to achieve this would be appreciated!

But he didn't give a more precise description, so I'm not completely sure they're what he meant. I've generally been pretty permissive on adding useful helpers to this library even if they can be built from primitives (e.g. `maybe`, `oneIn`).

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
My take:
- `scanOverList` is very specific. Is anybody even using `List.scanl`? If not, why would a randomized version of it be of interest?
- `foldOverList` probably has uses. But maybe add it only after you have at least one not completely artificial example? The function name seems inappropriate to me. Why is `List` part of the name? The type already tells us that we are not folding over a tree or whatnot.
- `mapOverList` has uses. But actually I would not introduce that function, instead introduce a function `combine : List (Generator a) -> Generator (List a)`. The `mapOverList` is then simply: `mapOverList f = List.map f >> Random.combine`. The name `combine` is in line with the corresponding function from http://package.elm-lang.org/packages/elm-community/maybe-extra (where `mapOverList` is called `traverse`) as well as with the corresponding function from http://package.elm-lang.org/packages/elm-community/result-extra and also with the corresponding function as it was in http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra. Oddly, in http://package.elm-lang.org/packages/elm-community/random-extra the corresponding function is called `together`. I think it should be called `combine` there as well. In `core`, the corresponding function on `Task`s is called `Task.sequence`.

**Comment by nphollon** [comment]
I will second Janis's points.

Before actually looking at the commit, I had been hoping for a different sort of `foldOverList`, one which would help me refactor this code:

```
spawn : Int -> Model -> Model
spawn n model =
    let
        ( positions, newSeed ) =
            randomPosition
                |> Random.list n
                |> flip Random.step model.seed
    in
        List.foldl
            (\p m ->
                { m
                    | bodies =
                        Dict.insert m.nextId (body p) m.bodies
                    , nextId = m.nextId + 1
                }
            )
            { model | seed = newSeed }
            positions


randomPosition : Generator Position

body : Position -> Body
```

This is the sort of thing I've had to puzzle over a few times, finding a clean way to transition from generating a random list to updating my model. Could it be that this is what the mystery man was looking for?

Two possible formulations come to mind:

`foldOverList : (a -> b -> b) -> b -> Int -> Generator a -> Generator b`

`foldOverList : (a -> r -> b -> b) -> b -> Generator r -> List a -> Generator b`

**Comment by xarvh** [comment]
I found myself writing a `mapList : (List a -> b) -> List (Generator a) -> Generator b` which, per @jvoigtlaender's post could be implemented via `mapList f = combine >> (Random.map f)` so yes, I'd find it very useful.
If @mgold needs help I'm happy to.

**Comment by xarvh** [comment]
(Also, would it be worth to export the `Generator` constructor? Right now implementing new compositors is not very easy...)

**Comment by mgold** [comment]
@xarvh Thanks for your offer to help, I think I've got this but I'll let you know.

I'd really like to keep `Generator` opaque to keep people from meddling with the RNG internals (you'd have to expose `Seed` too for this to be useful right?). So ... is there a more specific argument you can make for it, maybe?

**Comment by xarvh** [comment]
@mgold if `combine` gets added then all my use cases are neatly covered and I won't be able to make any argument. =)

This said, `combine` (and, I assume, any other custom composers)  can be implemented without the `Seed` constructor:

```
combine : List (Generator a) -> Generator (List a)
combine generators =
    let
        applyGenerator (Generator generator) ( values, oldSeed ) =
            let ( value, newSeed ) = generator oldSeed
            in ( value :: values, newSeed )

        generator oldSeed =
            List.foldr applyGenerator ( [], oldSeed ) generators
    in
        Generator generator
```

All composers just pass the seed around, to be honest I don't think there is any need to encapsulate the `Generator` type, only `Seed`.

**Pull request closed without merging**
